spring:
  application:
    name: account-service
  config:
    import:
    - configserver:http://localhost:8888
  cloud:
    config:
      password: passowrd # ${CONFIG_SERVICE_PASSWORD}
      username: user